// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPO-1GqDoRdNzmZcXDYAdJHnr-R6XhH9k',
    appId: '1:337689263237:web:d323230c7da5d565537dec',
    messagingSenderId: '337689263237',
    projectId: 'fir-flutter-codelab-6d2ac',
    authDomain: 'fir-flutter-codelab-6d2ac.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6d2ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvQ_Pw7Ka3Of92E0zEmcp8908Vs3PtxU',
    appId: '1:337689263237:android:993466abacc47686537dec',
    messagingSenderId: '337689263237',
    projectId: 'fir-flutter-codelab-6d2ac',
    storageBucket: 'fir-flutter-codelab-6d2ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYddphuG0E9VgAyFchB6knwKBJgOqhKw',
    appId: '1:337689263237:ios:d538c81b915d4bb5537dec',
    messagingSenderId: '337689263237',
    projectId: 'fir-flutter-codelab-6d2ac',
    storageBucket: 'fir-flutter-codelab-6d2ac.appspot.com',
    iosClientId: '337689263237-efm2e2snh1mvp6p4cin4q8mpbhjrepjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYddphuG0E9VgAyFchB6knwKBJgOqhKw',
    appId: '1:337689263237:ios:d538c81b915d4bb5537dec',
    messagingSenderId: '337689263237',
    projectId: 'fir-flutter-codelab-6d2ac',
    storageBucket: 'fir-flutter-codelab-6d2ac.appspot.com',
    iosClientId: '337689263237-efm2e2snh1mvp6p4cin4q8mpbhjrepjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
